<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/SOA_Training/DB_Adopter_Insert/Insert_BPELProcess1"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/Insert_BPELProcess1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="StudentCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/Insert_BPELProcess1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="StudentCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU NOV 21 11:11:10 IST 2024].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <xsl:for-each select="">
         <ns0:StudentCollection>
            <xsl:for-each select="ns0:StudentCollection/ns0:Student">
               <ns0:Student>
                  <ns0:stuId>
                     <xsl:value-of select="ns0:stuId"/>
                  </ns0:stuId>
                  <xsl:if test="ns0:stuName">
                     <xsl:if test="ns0:stuName">
                        <ns0:stuName>
                           <xsl:if test="ns0:stuName/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="ns0:stuName/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="ns0:stuName"/>
                           <xsl:value-of select="ns0:stuName"/>
                        </ns0:stuName>
                     </xsl:if>
                  </xsl:if>
                  <xsl:if test="ns0:stuAge">
                     <xsl:if test="ns0:stuAge">
                        <ns0:stuAge>
                           <xsl:if test="ns0:stuAge/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="ns0:stuAge/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="ns0:stuAge"/>
                           <xsl:value-of select="ns0:stuAge"/>
                        </ns0:stuAge>
                     </xsl:if>
                  </xsl:if>
               </ns0:Student>
            </xsl:for-each>
         </ns0:StudentCollection>
      </xsl:for-each>
   </xsl:template>
</xsl:stylesheet>
