<wsdl:definitions
     name="SelectQuery"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_Training/Db_AdopterDemo/SelectQuery"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_Training/Db_AdopterDemo/SelectQuery"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectQuery"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="SelectQuery_plt" >
    <plt:role name="SelectQuery_role" >
      <plt:portType name="tns:SelectQuery_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectQuery" schemaLocation="../Schemas/SelectQuery_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="SelectQuerySelect_inputParameters">
        <wsdl:part name="SelectQuerySelect_inputParameters" element="top:SelectQuerySelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EmployeeCollection_msg">
        <wsdl:part name="EmployeeCollection" element="top:EmployeeCollection"/>
    </wsdl:message>
    <wsdl:portType name="SelectQuery_ptt">
        <wsdl:operation name="SelectQuerySelect">
            <wsdl:input message="tns:SelectQuerySelect_inputParameters"/>
            <wsdl:output message="tns:EmployeeCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
